name: video_browser
description: Blindside Coding Challenge.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_svg: ^1.1.0
  inview_notifier_list: ^3.0.0
  random_date: ^0.0.7
  timeago: ^3.2.2
  video_player: ^2.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/brand/
    - assets/example/
